# Generated by Django 2.0.6 on 2018-07-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='final_date',
            field=models.DateTimeField(verbose_name='Data final'),
        ),
    ]
