# Generated by Django 2.0.6 on 2018-07-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='final_date',
            field=models.DateField(verbose_name='Data final'),
        ),
    ]
