# Generated by Django 2.0.6 on 2018-07-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20180718_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('C', 'Concluída'), ('R', 'Cancelada'), ('A', 'Em andamento')], default='A', max_length=1, verbose_name='Status'),
        ),
    ]
